//export const 
armazen = [
    {
      pergunta: "Qual o nome do criador(a) de Steven Universo?",
      resposta: "Rebecca Sugar",
      alternativa1: "Michaela Dietz",
      alternativa2: "Sarah Stiles",
      alternativa3: "Pendleton Ward",
      dificuldade: "F",
    },
    {
      pergunta: "Qual a primeira fusão a aparecer?",
      resposta: "Garnet",
      alternativa1: "Opal",
      alternativa2: "Stevonnie",
      alternativa3: "Sugilite",
      dificuldade: "F",
    },
    {
      pergunta: "Por quais gems a Garnet é formada?",
      resposta: "Rubi e Safira",
      alternativa1: "Rubi e Nefrita",
      alternativa2: "Safira e Nefrita",
      alternativa3: "Nefrita e Larimar",
      dificuldade: "F",
    },
    {
      pergunta: "Por quantas gems Fluorita é formada?",
      resposta: "7",
      alternativa1: "5",
      alternativa2: "6",
      alternativa3: "3",
      dificuldade: "F",
    },
    {
      pergunta: "Qual humano era perdidamente apaixonado por Garnet?",
      resposta: "Jamie",
      alternativa1: "Buck",
      alternativa2: "Peedee",
      alternativa3: "Lars",
      dificuldade: "F",
    },
    {
      pergunta: "Qual o nome do dono(a) do parque de diversões de Beach City?",
      resposta: "Harold Smiley",
      alternativa1: "Buddy Buddwick",
      alternativa2: "Connie Maheswaran",
      alternativa3: "Andy DeMayo",
      dificuldade: "F",
    },
    {
      pergunta: "Qual o emprego de Barbara Miller?",
      resposta: "Carteira",
      alternativa1: "Cantora",
      alternativa2: "Prefeita",
      alternativa3: "Garçonet",
      dificuldade: "F",
    },
    {
      pergunta: "Com quem Steven se fundiu primeiro?",
      resposta: "Connie",
      alternativa1: "Pérola",
      alternativa2: "Ametista",
      alternativa3: "Garnet",
      dificuldade: "F",
    },
    {
      pergunta: 'Quem "estilhaçou" Pink Diamond?',
      resposta: "Pérola",
      alternativa1: "Rose Quarts",
      alternativa2: "Jasper",
      alternativa3: "Diamente Branco",
      dificuldade: "M",
    },
    {
      pergunta: "Quantas Diamantes existem?",
      resposta: "4",
      alternativa1: "2",
      alternativa2: "1",
      alternativa3: "3",
      dificuldade: "F",
    },
    {
      pergunta: "Qual foi a primeira coisa que o Steven comeu na série?",
      resposta: "As sobras",
      alternativa1: "Rosquinha do Big Risquinha",
      alternativa2: "Pizza do Peixe cozido",
      alternativa3: "Biscoito Gatinho",
      dificuldade: "M",
    },
    {
      pergunta: "O que ou quem foi que as gems enfrentaram primeiro na série?",
      resposta: "Um olho vermelho",
      alternativa1: "Um olho gigante",
      alternativa2: "Uma gem corrompida",
      alternativa3: "Uma gems que queria destruir eles",
      dificuldade: "M",
    },
    {
      pergunta: "Qual a primeira musica que toca na séria não sendo a abertura?",
      resposta: "Minha van vai pro seu coração",
      alternativa1: "Nos somos as cristal Gems",
      alternativa2: "Destino",
      alternativa3: "Mulher Gigante",
      dificuldade: "M",
    },
    {
      pergunta: "Qual episodio a Peridote aparece pela primeira vez?",
      resposta: "Trasportadores",
      alternativa1: "Visitante do espaço",
      alternativa2: "Amigos de Bolha",
      alternativa3: "Perdidos no espaço",
      dificuldade: "M",
    },
    {
      pergunta: "O que são fragmento?",
      resposta: "Pedaços de gems que não tem consciência",
      alternativa1: "Pedaços de gems que tem consciência",
      alternativa2: "Gems corrompidas",
      alternativa3: "Um tipo de rosquinha",
      dificuldade: "F",
    },
    {
      pergunta: "Steven tem um animal de estimação mágico deixado para ele por sua mãe, que animal é esse?",
      resposta: "Leão",
      alternativa1: "Cachorro",
      alternativa2: "Gato",
      alternativa3: "Centípoda",
      dificuldade: "F",
    },
    {
      pergunta: "Onde estava a espada de Rose Quatz?",
      resposta: "No Leão",
      alternativa1: "No lugar secreto de armas",
      alternativa2: "No quarto da Ametista",
      alternativa3: "No Quarto de Rose",
      dificuldade: "F",
    },
    {
      pergunta: "Qual frase ativou o canhão de laser de Rose Quartz?",
      resposta: "Se o porco inteiro fosse perfeito não haveria cachorro - quentes",
      alternativa1: "Não se pode ganhar todas",
      alternativa2: "Ativar",
      alternativa3: "Não morda mais do que consegue engolir",
      dificuldade: "D",
    },
    {
      pergunta: "Qual epsódio Steven se funde com todas as Crystal Gems?",
      resposta: "Change Your Mind",
      alternativa1: "Escapism",
      alternativa2: "Off Colors",
      alternativa3: "Lars Head",
      dificuldade: "M",
    },
    {
      pergunta: "Onde estava o palanque quebrado de Pink Diamond?",
      resposta: "Coréia do Sul",
      alternativa1: "Rússia",
      alternativa2: "Beach City",
      alternativa3: "Empire City",
      dificuldade: "M",
    },
    {
      pergunta: "Qual o nome do episódio em que a Blue Diamond aparece?(Sem mostrar o seu rosto)",
      resposta: "The Answer",
      alternativa1: "Reunited",
      alternativa2: "Lars Head",
      alternativa3: "The Trial",
      dificuldade: "D",
    },
    {
      pergunta: "Qual o nome da fusão de Garnet e Steven",
      resposta: "Sunstone",
      alternativa1: "Obsidian",
      alternativa2: "Sugilite",
      alternativa3: "Alexandrite",
      dificuldade: "M",
    },
    {
      pergunta: "Qual o nome da fusão de Pérola e Rose Quarts",
      resposta: "Rainbow",
      alternativa1: "Smoky Quartz",
      alternativa2: "Sardonyx",
      alternativa3: "Obsidian",
      dificuldade: "F",
    },
    {
      pergunta: "Qual é a arma da Obsidian?",
      resposta: "Uma Espada",
      alternativa1: "Um Tridente",
      alternativa2: "Uma Besta",
      alternativa3: "Uma Picareta",
      dificuldade: "M",
    },
    {
      pergunta: "Qual o verdadeiro sobrenome de Greg, visto em Gem Harvest?",
      resposta: "DeMayo",
      alternativa1: "Universo",
      alternativa2: "Quarts",
      alternativa3: "Jones",
      dificuldade: "M",
    },
    {
      pergunta: "Do que Peridot chamou a Yellow Diamont em Mensagem Recebida",
      resposta: "Tonta",
      alternativa1: "Lesada",
      alternativa2: "Pescoçuda",
      alternativa3: "Burra",
      dificuldade: "M",
    },
    {
      pergunta: "Qual o instrumento que Steven mais toca?",
      resposta: "Ukulele",
      alternativa1: "Violão",
      alternativa2: "Guitarra",
      alternativa3: "Bateria",
      dificuldade: "F",
    },
    {
      pergunta: "Qual o estilo de dança e de luta da Pérola?",
      resposta: "Balé",
      alternativa1: "Rock",
      alternativa2: "K-Pop",
      alternativa3: "Alternativo",
      dificuldade: "F",
    },
    {
      pergunta: "Opal é a fusão de quais gems?",
      resposta: "Pérola e Ametista",
      alternativa1: "Pérola e Steven",
      alternativa2: "Pérola e Connie",
      alternativa3: "Ametista e Steven",
      dificuldade: "F",
    },
    
  ]; 
  console.log(armazen.length)