export const armazen = [
    {
      pergunta: "Qual o nome do criador(a) de Steven Universo ?",
      resposta: "Rebecca Sugar",
      alternativa1: "Michaela Dietz",
      alternativa2: "Sarah Stiles",
      alternativa3: "Pendleton Ward",
      dificuldade: "F",
    },
    {
      pergunta: "Qual a primeira fusão a aparecer ?",
      resposta: "Garnet",
      alternativa1: "Opal",
      alternativa2: "Stevonnie",
      alternativa3: "Sugilite",
      dificuldade: "F",
    },
    {
      pergunta: "Por quais gems a Garnet é formada ?",
      resposta: "Rubi e Safira",
      alternativa1: "Rubi e Nefrita",
      alternativa2: "Safira e Nefrita",
      alternativa3: "Nefrita e Larimar",
      dificuldade: "F",
    },
    {
      pergunta: "Por quantas gems Fluorita é formada ?",
      resposta: "7",
      alternativa1: "5",
      alternativa2: "6",
      alternativa3: "3",
      dificuldade: "F",
    },
    {
      pergunta: "Qual humano era perdidamente apaixonado por Garnet?",
      resposta: "Jamie",
      alternativa1: "Buck",
      alternativa2: "Peedee",
      alternativa3: "Lars",
      dificuldade: "F",
    },
    {
      pergunta: "Qual o nome do dono(a) do parque de diversões de Beach City ?",
      resposta: "Harold Smiley",
      alternativa1: "Buddy Buddwick",
      alternativa2: "Connie Maheswaran",
      alternativa3: "Andy DeMayo",
      dificuldade: "F",
    },
    {
      pergunta: "Qual o emprego de Barbara Miller ?",
      resposta: "Carteira",
      alternativa1: "Cantora",
      alternativa2: "Prefeita",
      alternativa3: "Garçonet",
      dificuldade: "F",
    },
    {
      pergunta: "Com quem Steven se fundiu primeiro ?",
      resposta: "Connie",
      alternativa1: "Pérola",
      alternativa2: "Ametista",
      alternativa3: "Garnet",
      dificuldade: "F",
    },
    {
      pergunta: 'Quem "estilhaçou" Pink Diamond ?',
      resposta: "Pérola",
      alternativa1: "Rose Quarts",
      alternativa2: "Jasper",
      alternativa3: "Diamente Branco",
      dificuldade: "F",
    },
    {
      pergunta: "Quantas Diamantes existem ?",
      resposta: "4",
      alternativa1: "2",
      alternativa2: "1",
      alternativa3: "3",
      dificuldade: "F",
    },
  ];